export const CreditListData = [
    {
      "client_id": "654321",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    },
    {
      "client_id": "0123456",
      "contract_id": "0123456",
      "debtor_type": "Розничный",
      "credit_type": "Потребительский",
      "product_type": "Залоговый",
      "VBS": "123",
      "RAM": "123",
      "RTAM": "123",
      "currency": "$",
      "PD": "123",
      "LGD": "123"
    }
  ]
  