/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as BasicLayoutImport } from './routes/_basic-layout'
import { Route as R404Import } from './routes/404'
import { Route as IndexImport } from './routes/index'
import { Route as BasicLayoutProfileImport } from './routes/_basic-layout/profile'
import { Route as BasicLayoutDatasetImport } from './routes/_basic-layout/dataset'
import { Route as BasicLayoutAppsImport } from './routes/_basic-layout/apps'
import { Route as BasicLayoutAnalyzerImport } from './routes/_basic-layout/analyzer'
import { Route as BasicLayoutReportsIndexImport } from './routes/_basic-layout/reports/index'
import { Route as BasicLayoutReportsReportIdIndexImport } from './routes/_basic-layout/reports/$reportId/index'
import { Route as BasicLayoutReportsReportIdStressTestingImport } from './routes/_basic-layout/reports/$reportId/stress-testing'
import { Route as BasicLayoutReportsReportIdNewReportImport } from './routes/_basic-layout/reports/$reportId/new-report'
import { Route as BasicLayoutReportsReportIdDashboardImport } from './routes/_basic-layout/reports/$reportId/dashboard'
import { Route as BasicLayoutReportsReportIdCreditListImport } from './routes/_basic-layout/reports/$reportId/credit-list'
import { Route as BasicLayoutReportsReportIdBiAnalyticsImport } from './routes/_basic-layout/reports/$reportId/bi-analytics'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const BasicLayoutRoute = BasicLayoutImport.update({
  id: '/_basic-layout',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BasicLayoutProfileRoute = BasicLayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => BasicLayoutRoute,
} as any)

const BasicLayoutDatasetRoute = BasicLayoutDatasetImport.update({
  path: '/dataset',
  getParentRoute: () => BasicLayoutRoute,
} as any)

const BasicLayoutAppsRoute = BasicLayoutAppsImport.update({
  path: '/apps',
  getParentRoute: () => BasicLayoutRoute,
} as any)

const BasicLayoutAnalyzerRoute = BasicLayoutAnalyzerImport.update({
  path: '/analyzer',
  getParentRoute: () => BasicLayoutRoute,
} as any)

const BasicLayoutReportsIndexRoute = BasicLayoutReportsIndexImport.update({
  path: '/reports/',
  getParentRoute: () => BasicLayoutRoute,
} as any)

const BasicLayoutReportsReportIdIndexRoute =
  BasicLayoutReportsReportIdIndexImport.update({
    path: '/reports/$reportId/',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

const BasicLayoutReportsReportIdStressTestingRoute =
  BasicLayoutReportsReportIdStressTestingImport.update({
    path: '/reports/$reportId/stress-testing',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

const BasicLayoutReportsReportIdNewReportRoute =
  BasicLayoutReportsReportIdNewReportImport.update({
    path: '/reports/$reportId/new-report',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

const BasicLayoutReportsReportIdDashboardRoute =
  BasicLayoutReportsReportIdDashboardImport.update({
    path: '/reports/$reportId/dashboard',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

const BasicLayoutReportsReportIdCreditListRoute =
  BasicLayoutReportsReportIdCreditListImport.update({
    path: '/reports/$reportId/credit-list',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

const BasicLayoutReportsReportIdBiAnalyticsRoute =
  BasicLayoutReportsReportIdBiAnalyticsImport.update({
    path: '/reports/$reportId/bi-analytics',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_basic-layout': {
      id: '/_basic-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BasicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_basic-layout/analyzer': {
      id: '/_basic-layout/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof BasicLayoutAnalyzerImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/apps': {
      id: '/_basic-layout/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof BasicLayoutAppsImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/dataset': {
      id: '/_basic-layout/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof BasicLayoutDatasetImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/profile': {
      id: '/_basic-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof BasicLayoutProfileImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/': {
      id: '/_basic-layout/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof BasicLayoutReportsIndexImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/$reportId/bi-analytics': {
      id: '/_basic-layout/reports/$reportId/bi-analytics'
      path: '/reports/$reportId/bi-analytics'
      fullPath: '/reports/$reportId/bi-analytics'
      preLoaderRoute: typeof BasicLayoutReportsReportIdBiAnalyticsImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/$reportId/credit-list': {
      id: '/_basic-layout/reports/$reportId/credit-list'
      path: '/reports/$reportId/credit-list'
      fullPath: '/reports/$reportId/credit-list'
      preLoaderRoute: typeof BasicLayoutReportsReportIdCreditListImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/$reportId/dashboard': {
      id: '/_basic-layout/reports/$reportId/dashboard'
      path: '/reports/$reportId/dashboard'
      fullPath: '/reports/$reportId/dashboard'
      preLoaderRoute: typeof BasicLayoutReportsReportIdDashboardImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/$reportId/new-report': {
      id: '/_basic-layout/reports/$reportId/new-report'
      path: '/reports/$reportId/new-report'
      fullPath: '/reports/$reportId/new-report'
      preLoaderRoute: typeof BasicLayoutReportsReportIdNewReportImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/$reportId/stress-testing': {
      id: '/_basic-layout/reports/$reportId/stress-testing'
      path: '/reports/$reportId/stress-testing'
      fullPath: '/reports/$reportId/stress-testing'
      preLoaderRoute: typeof BasicLayoutReportsReportIdStressTestingImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_basic-layout/reports/$reportId/': {
      id: '/_basic-layout/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof BasicLayoutReportsReportIdIndexImport
      parentRoute: typeof BasicLayoutImport
    }
  }
}

// Create and export the route tree

interface BasicLayoutRouteChildren {
  BasicLayoutAnalyzerRoute: typeof BasicLayoutAnalyzerRoute
  BasicLayoutAppsRoute: typeof BasicLayoutAppsRoute
  BasicLayoutDatasetRoute: typeof BasicLayoutDatasetRoute
  BasicLayoutProfileRoute: typeof BasicLayoutProfileRoute
  BasicLayoutReportsIndexRoute: typeof BasicLayoutReportsIndexRoute
  BasicLayoutReportsReportIdBiAnalyticsRoute: typeof BasicLayoutReportsReportIdBiAnalyticsRoute
  BasicLayoutReportsReportIdCreditListRoute: typeof BasicLayoutReportsReportIdCreditListRoute
  BasicLayoutReportsReportIdDashboardRoute: typeof BasicLayoutReportsReportIdDashboardRoute
  BasicLayoutReportsReportIdNewReportRoute: typeof BasicLayoutReportsReportIdNewReportRoute
  BasicLayoutReportsReportIdStressTestingRoute: typeof BasicLayoutReportsReportIdStressTestingRoute
  BasicLayoutReportsReportIdIndexRoute: typeof BasicLayoutReportsReportIdIndexRoute
}

const BasicLayoutRouteChildren: BasicLayoutRouteChildren = {
  BasicLayoutAnalyzerRoute: BasicLayoutAnalyzerRoute,
  BasicLayoutAppsRoute: BasicLayoutAppsRoute,
  BasicLayoutDatasetRoute: BasicLayoutDatasetRoute,
  BasicLayoutProfileRoute: BasicLayoutProfileRoute,
  BasicLayoutReportsIndexRoute: BasicLayoutReportsIndexRoute,
  BasicLayoutReportsReportIdBiAnalyticsRoute:
    BasicLayoutReportsReportIdBiAnalyticsRoute,
  BasicLayoutReportsReportIdCreditListRoute:
    BasicLayoutReportsReportIdCreditListRoute,
  BasicLayoutReportsReportIdDashboardRoute:
    BasicLayoutReportsReportIdDashboardRoute,
  BasicLayoutReportsReportIdNewReportRoute:
    BasicLayoutReportsReportIdNewReportRoute,
  BasicLayoutReportsReportIdStressTestingRoute:
    BasicLayoutReportsReportIdStressTestingRoute,
  BasicLayoutReportsReportIdIndexRoute: BasicLayoutReportsReportIdIndexRoute,
}

const BasicLayoutRouteWithChildren = BasicLayoutRoute._addFileChildren(
  BasicLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof BasicLayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/analyzer': typeof BasicLayoutAnalyzerRoute
  '/apps': typeof BasicLayoutAppsRoute
  '/dataset': typeof BasicLayoutDatasetRoute
  '/profile': typeof BasicLayoutProfileRoute
  '/reports': typeof BasicLayoutReportsIndexRoute
  '/reports/$reportId/bi-analytics': typeof BasicLayoutReportsReportIdBiAnalyticsRoute
  '/reports/$reportId/credit-list': typeof BasicLayoutReportsReportIdCreditListRoute
  '/reports/$reportId/dashboard': typeof BasicLayoutReportsReportIdDashboardRoute
  '/reports/$reportId/new-report': typeof BasicLayoutReportsReportIdNewReportRoute
  '/reports/$reportId/stress-testing': typeof BasicLayoutReportsReportIdStressTestingRoute
  '/reports/$reportId': typeof BasicLayoutReportsReportIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '': typeof BasicLayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/analyzer': typeof BasicLayoutAnalyzerRoute
  '/apps': typeof BasicLayoutAppsRoute
  '/dataset': typeof BasicLayoutDatasetRoute
  '/profile': typeof BasicLayoutProfileRoute
  '/reports': typeof BasicLayoutReportsIndexRoute
  '/reports/$reportId/bi-analytics': typeof BasicLayoutReportsReportIdBiAnalyticsRoute
  '/reports/$reportId/credit-list': typeof BasicLayoutReportsReportIdCreditListRoute
  '/reports/$reportId/dashboard': typeof BasicLayoutReportsReportIdDashboardRoute
  '/reports/$reportId/new-report': typeof BasicLayoutReportsReportIdNewReportRoute
  '/reports/$reportId/stress-testing': typeof BasicLayoutReportsReportIdStressTestingRoute
  '/reports/$reportId': typeof BasicLayoutReportsReportIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_basic-layout': typeof BasicLayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_basic-layout/analyzer': typeof BasicLayoutAnalyzerRoute
  '/_basic-layout/apps': typeof BasicLayoutAppsRoute
  '/_basic-layout/dataset': typeof BasicLayoutDatasetRoute
  '/_basic-layout/profile': typeof BasicLayoutProfileRoute
  '/_basic-layout/reports/': typeof BasicLayoutReportsIndexRoute
  '/_basic-layout/reports/$reportId/bi-analytics': typeof BasicLayoutReportsReportIdBiAnalyticsRoute
  '/_basic-layout/reports/$reportId/credit-list': typeof BasicLayoutReportsReportIdCreditListRoute
  '/_basic-layout/reports/$reportId/dashboard': typeof BasicLayoutReportsReportIdDashboardRoute
  '/_basic-layout/reports/$reportId/new-report': typeof BasicLayoutReportsReportIdNewReportRoute
  '/_basic-layout/reports/$reportId/stress-testing': typeof BasicLayoutReportsReportIdStressTestingRoute
  '/_basic-layout/reports/$reportId/': typeof BasicLayoutReportsReportIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | ''
    | '/auth'
    | '/analyzer'
    | '/apps'
    | '/dataset'
    | '/profile'
    | '/reports'
    | '/reports/$reportId/bi-analytics'
    | '/reports/$reportId/credit-list'
    | '/reports/$reportId/dashboard'
    | '/reports/$reportId/new-report'
    | '/reports/$reportId/stress-testing'
    | '/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | ''
    | '/auth'
    | '/analyzer'
    | '/apps'
    | '/dataset'
    | '/profile'
    | '/reports'
    | '/reports/$reportId/bi-analytics'
    | '/reports/$reportId/credit-list'
    | '/reports/$reportId/dashboard'
    | '/reports/$reportId/new-report'
    | '/reports/$reportId/stress-testing'
    | '/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_basic-layout'
    | '/auth'
    | '/_basic-layout/analyzer'
    | '/_basic-layout/apps'
    | '/_basic-layout/dataset'
    | '/_basic-layout/profile'
    | '/_basic-layout/reports/'
    | '/_basic-layout/reports/$reportId/bi-analytics'
    | '/_basic-layout/reports/$reportId/credit-list'
    | '/_basic-layout/reports/$reportId/dashboard'
    | '/_basic-layout/reports/$reportId/new-report'
    | '/_basic-layout/reports/$reportId/stress-testing'
    | '/_basic-layout/reports/$reportId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BasicLayoutRoute: typeof BasicLayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BasicLayoutRoute: BasicLayoutRouteWithChildren,
  AuthRoute: AuthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/404",
        "/_basic-layout",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/404": {
      "filePath": "404.tsx"
    },
    "/_basic-layout": {
      "filePath": "_basic-layout.tsx",
      "children": [
        "/_basic-layout/analyzer",
        "/_basic-layout/apps",
        "/_basic-layout/dataset",
        "/_basic-layout/profile",
        "/_basic-layout/reports/",
        "/_basic-layout/reports/$reportId/bi-analytics",
        "/_basic-layout/reports/$reportId/credit-list",
        "/_basic-layout/reports/$reportId/dashboard",
        "/_basic-layout/reports/$reportId/new-report",
        "/_basic-layout/reports/$reportId/stress-testing",
        "/_basic-layout/reports/$reportId/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/_basic-layout/analyzer": {
      "filePath": "_basic-layout/analyzer.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/apps": {
      "filePath": "_basic-layout/apps.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/dataset": {
      "filePath": "_basic-layout/dataset.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/profile": {
      "filePath": "_basic-layout/profile.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/": {
      "filePath": "_basic-layout/reports/index.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/$reportId/bi-analytics": {
      "filePath": "_basic-layout/reports/$reportId/bi-analytics.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/$reportId/credit-list": {
      "filePath": "_basic-layout/reports/$reportId/credit-list.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/$reportId/dashboard": {
      "filePath": "_basic-layout/reports/$reportId/dashboard.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/$reportId/new-report": {
      "filePath": "_basic-layout/reports/$reportId/new-report.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/$reportId/stress-testing": {
      "filePath": "_basic-layout/reports/$reportId/stress-testing.tsx",
      "parent": "/_basic-layout"
    },
    "/_basic-layout/reports/$reportId/": {
      "filePath": "_basic-layout/reports/$reportId/index.tsx",
      "parent": "/_basic-layout"
    }
  }
}
ROUTE_MANIFEST_END */
