/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReportsImport } from './routes/reports'
import { Route as AuthImport } from './routes/auth'
import { Route as AppsImport } from './routes/apps'
import { Route as LayoutWithoutSidebarImport } from './routes/_layout-without-sidebar'
import { Route as CustomLayoutImport } from './routes/_custom-layout'
import { Route as ClearLayoutImport } from './routes/_clear-layout'
import { Route as BasicLayoutImport } from './routes/_basic-layout'
import { Route as IndexImport } from './routes/index'
import { Route as ClearLayoutProfileImport } from './routes/_clear-layout/profile'
import { Route as BasicLayoutReportsReportIdIndexImport } from './routes/_basic-layout/reports/$reportId/index'
import { Route as LayoutWithoutSidebarReportsReportsIdStressTestingImport } from './routes/_layout-without-sidebar/reports/$reportsId/stress-testing'
import { Route as LayoutWithoutSidebarReportsReportsIdBiAnalyticsImport } from './routes/_layout-without-sidebar/reports/$reportsId/bi-analytics'
import { Route as CustomLayoutReportsReportIdNewReportImport } from './routes/_custom-layout/reports/$reportId/new-report'
import { Route as ClearLayoutReportsReportIdCreditListImport } from './routes/_clear-layout/reports/$reportId/credit-list'
import { Route as BasicLayoutReportsReportIdDashboardImport } from './routes/_basic-layout/reports/$reportId/dashboard'

// Create/Update Routes

const ReportsRoute = ReportsImport.update({
  path: '/reports',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppsRoute = AppsImport.update({
  path: '/apps',
  getParentRoute: () => rootRoute,
} as any)

const LayoutWithoutSidebarRoute = LayoutWithoutSidebarImport.update({
  id: '/_layout-without-sidebar',
  getParentRoute: () => rootRoute,
} as any)

const CustomLayoutRoute = CustomLayoutImport.update({
  id: '/_custom-layout',
  getParentRoute: () => rootRoute,
} as any)

const ClearLayoutRoute = ClearLayoutImport.update({
  id: '/_clear-layout',
  getParentRoute: () => rootRoute,
} as any)

const BasicLayoutRoute = BasicLayoutImport.update({
  id: '/_basic-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClearLayoutProfileRoute = ClearLayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => ClearLayoutRoute,
} as any)

const BasicLayoutReportsReportIdIndexRoute =
  BasicLayoutReportsReportIdIndexImport.update({
    path: '/reports/$reportId/',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

const LayoutWithoutSidebarReportsReportsIdStressTestingRoute =
  LayoutWithoutSidebarReportsReportsIdStressTestingImport.update({
    path: '/reports/$reportsId/stress-testing',
    getParentRoute: () => LayoutWithoutSidebarRoute,
  } as any)

const LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute =
  LayoutWithoutSidebarReportsReportsIdBiAnalyticsImport.update({
    path: '/reports/$reportsId/bi-analytics',
    getParentRoute: () => LayoutWithoutSidebarRoute,
  } as any)

const CustomLayoutReportsReportIdNewReportRoute =
  CustomLayoutReportsReportIdNewReportImport.update({
    path: '/reports/$reportId/new-report',
    getParentRoute: () => CustomLayoutRoute,
  } as any)

const ClearLayoutReportsReportIdCreditListRoute =
  ClearLayoutReportsReportIdCreditListImport.update({
    path: '/reports/$reportId/credit-list',
    getParentRoute: () => ClearLayoutRoute,
  } as any)

const BasicLayoutReportsReportIdDashboardRoute =
  BasicLayoutReportsReportIdDashboardImport.update({
    path: '/reports/$reportId/dashboard',
    getParentRoute: () => BasicLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_basic-layout': {
      id: '/_basic-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BasicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_clear-layout': {
      id: '/_clear-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ClearLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_custom-layout': {
      id: '/_custom-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CustomLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout-without-sidebar': {
      id: '/_layout-without-sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutWithoutSidebarImport
      parentRoute: typeof rootRoute
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsImport
      parentRoute: typeof rootRoute
    }
    '/_clear-layout/profile': {
      id: '/_clear-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ClearLayoutProfileImport
      parentRoute: typeof ClearLayoutImport
    }
    '/_basic-layout/reports/$reportId/dashboard': {
      id: '/_basic-layout/reports/$reportId/dashboard'
      path: '/reports/$reportId/dashboard'
      fullPath: '/reports/$reportId/dashboard'
      preLoaderRoute: typeof BasicLayoutReportsReportIdDashboardImport
      parentRoute: typeof BasicLayoutImport
    }
    '/_clear-layout/reports/$reportId/credit-list': {
      id: '/_clear-layout/reports/$reportId/credit-list'
      path: '/reports/$reportId/credit-list'
      fullPath: '/reports/$reportId/credit-list'
      preLoaderRoute: typeof ClearLayoutReportsReportIdCreditListImport
      parentRoute: typeof ClearLayoutImport
    }
    '/_custom-layout/reports/$reportId/new-report': {
      id: '/_custom-layout/reports/$reportId/new-report'
      path: '/reports/$reportId/new-report'
      fullPath: '/reports/$reportId/new-report'
      preLoaderRoute: typeof CustomLayoutReportsReportIdNewReportImport
      parentRoute: typeof CustomLayoutImport
    }
    '/_layout-without-sidebar/reports/$reportsId/bi-analytics': {
      id: '/_layout-without-sidebar/reports/$reportsId/bi-analytics'
      path: '/reports/$reportsId/bi-analytics'
      fullPath: '/reports/$reportsId/bi-analytics'
      preLoaderRoute: typeof LayoutWithoutSidebarReportsReportsIdBiAnalyticsImport
      parentRoute: typeof LayoutWithoutSidebarImport
    }
    '/_layout-without-sidebar/reports/$reportsId/stress-testing': {
      id: '/_layout-without-sidebar/reports/$reportsId/stress-testing'
      path: '/reports/$reportsId/stress-testing'
      fullPath: '/reports/$reportsId/stress-testing'
      preLoaderRoute: typeof LayoutWithoutSidebarReportsReportsIdStressTestingImport
      parentRoute: typeof LayoutWithoutSidebarImport
    }
    '/_basic-layout/reports/$reportId/': {
      id: '/_basic-layout/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof BasicLayoutReportsReportIdIndexImport
      parentRoute: typeof BasicLayoutImport
    }
  }
}

// Create and export the route tree

interface BasicLayoutRouteChildren {
  BasicLayoutReportsReportIdDashboardRoute: typeof BasicLayoutReportsReportIdDashboardRoute
  BasicLayoutReportsReportIdIndexRoute: typeof BasicLayoutReportsReportIdIndexRoute
}

const BasicLayoutRouteChildren: BasicLayoutRouteChildren = {
  BasicLayoutReportsReportIdDashboardRoute:
    BasicLayoutReportsReportIdDashboardRoute,
  BasicLayoutReportsReportIdIndexRoute: BasicLayoutReportsReportIdIndexRoute,
}

const BasicLayoutRouteWithChildren = BasicLayoutRoute._addFileChildren(
  BasicLayoutRouteChildren
)

interface ClearLayoutRouteChildren {
  ClearLayoutProfileRoute: typeof ClearLayoutProfileRoute
  ClearLayoutReportsReportIdCreditListRoute: typeof ClearLayoutReportsReportIdCreditListRoute
}

const ClearLayoutRouteChildren: ClearLayoutRouteChildren = {
  ClearLayoutProfileRoute: ClearLayoutProfileRoute,
  ClearLayoutReportsReportIdCreditListRoute:
    ClearLayoutReportsReportIdCreditListRoute,
}

const ClearLayoutRouteWithChildren = ClearLayoutRoute._addFileChildren(
  ClearLayoutRouteChildren
)

interface CustomLayoutRouteChildren {
  CustomLayoutReportsReportIdNewReportRoute: typeof CustomLayoutReportsReportIdNewReportRoute
}

const CustomLayoutRouteChildren: CustomLayoutRouteChildren = {
  CustomLayoutReportsReportIdNewReportRoute:
    CustomLayoutReportsReportIdNewReportRoute,
}

const CustomLayoutRouteWithChildren = CustomLayoutRoute._addFileChildren(
  CustomLayoutRouteChildren
)

interface LayoutWithoutSidebarRouteChildren {
  LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute: typeof LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute
  LayoutWithoutSidebarReportsReportsIdStressTestingRoute: typeof LayoutWithoutSidebarReportsReportsIdStressTestingRoute
}

const LayoutWithoutSidebarRouteChildren: LayoutWithoutSidebarRouteChildren = {
  LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute:
    LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute,
  LayoutWithoutSidebarReportsReportsIdStressTestingRoute:
    LayoutWithoutSidebarReportsReportsIdStressTestingRoute,
}

const LayoutWithoutSidebarRouteWithChildren =
  LayoutWithoutSidebarRoute._addFileChildren(LayoutWithoutSidebarRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutWithoutSidebarRouteWithChildren
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/profile': typeof ClearLayoutProfileRoute
  '/reports/$reportId/dashboard': typeof BasicLayoutReportsReportIdDashboardRoute
  '/reports/$reportId/credit-list': typeof ClearLayoutReportsReportIdCreditListRoute
  '/reports/$reportId/new-report': typeof CustomLayoutReportsReportIdNewReportRoute
  '/reports/$reportsId/bi-analytics': typeof LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute
  '/reports/$reportsId/stress-testing': typeof LayoutWithoutSidebarReportsReportsIdStressTestingRoute
  '/reports/$reportId': typeof BasicLayoutReportsReportIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutWithoutSidebarRouteWithChildren
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/profile': typeof ClearLayoutProfileRoute
  '/reports/$reportId/dashboard': typeof BasicLayoutReportsReportIdDashboardRoute
  '/reports/$reportId/credit-list': typeof ClearLayoutReportsReportIdCreditListRoute
  '/reports/$reportId/new-report': typeof CustomLayoutReportsReportIdNewReportRoute
  '/reports/$reportsId/bi-analytics': typeof LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute
  '/reports/$reportsId/stress-testing': typeof LayoutWithoutSidebarReportsReportsIdStressTestingRoute
  '/reports/$reportId': typeof BasicLayoutReportsReportIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_basic-layout': typeof BasicLayoutRouteWithChildren
  '/_clear-layout': typeof ClearLayoutRouteWithChildren
  '/_custom-layout': typeof CustomLayoutRouteWithChildren
  '/_layout-without-sidebar': typeof LayoutWithoutSidebarRouteWithChildren
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/_clear-layout/profile': typeof ClearLayoutProfileRoute
  '/_basic-layout/reports/$reportId/dashboard': typeof BasicLayoutReportsReportIdDashboardRoute
  '/_clear-layout/reports/$reportId/credit-list': typeof ClearLayoutReportsReportIdCreditListRoute
  '/_custom-layout/reports/$reportId/new-report': typeof CustomLayoutReportsReportIdNewReportRoute
  '/_layout-without-sidebar/reports/$reportsId/bi-analytics': typeof LayoutWithoutSidebarReportsReportsIdBiAnalyticsRoute
  '/_layout-without-sidebar/reports/$reportsId/stress-testing': typeof LayoutWithoutSidebarReportsReportsIdStressTestingRoute
  '/_basic-layout/reports/$reportId/': typeof BasicLayoutReportsReportIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/apps'
    | '/auth'
    | '/reports'
    | '/profile'
    | '/reports/$reportId/dashboard'
    | '/reports/$reportId/credit-list'
    | '/reports/$reportId/new-report'
    | '/reports/$reportsId/bi-analytics'
    | '/reports/$reportsId/stress-testing'
    | '/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/apps'
    | '/auth'
    | '/reports'
    | '/profile'
    | '/reports/$reportId/dashboard'
    | '/reports/$reportId/credit-list'
    | '/reports/$reportId/new-report'
    | '/reports/$reportsId/bi-analytics'
    | '/reports/$reportsId/stress-testing'
    | '/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/_basic-layout'
    | '/_clear-layout'
    | '/_custom-layout'
    | '/_layout-without-sidebar'
    | '/apps'
    | '/auth'
    | '/reports'
    | '/_clear-layout/profile'
    | '/_basic-layout/reports/$reportId/dashboard'
    | '/_clear-layout/reports/$reportId/credit-list'
    | '/_custom-layout/reports/$reportId/new-report'
    | '/_layout-without-sidebar/reports/$reportsId/bi-analytics'
    | '/_layout-without-sidebar/reports/$reportsId/stress-testing'
    | '/_basic-layout/reports/$reportId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicLayoutRoute: typeof BasicLayoutRouteWithChildren
  ClearLayoutRoute: typeof ClearLayoutRouteWithChildren
  CustomLayoutRoute: typeof CustomLayoutRouteWithChildren
  LayoutWithoutSidebarRoute: typeof LayoutWithoutSidebarRouteWithChildren
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  ReportsRoute: typeof ReportsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicLayoutRoute: BasicLayoutRouteWithChildren,
  ClearLayoutRoute: ClearLayoutRouteWithChildren,
  CustomLayoutRoute: CustomLayoutRouteWithChildren,
  LayoutWithoutSidebarRoute: LayoutWithoutSidebarRouteWithChildren,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  ReportsRoute: ReportsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_basic-layout",
        "/_clear-layout",
        "/_custom-layout",
        "/_layout-without-sidebar",
        "/apps",
        "/auth",
        "/reports"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_basic-layout": {
      "filePath": "_basic-layout.tsx",
      "children": [
        "/_basic-layout/reports/$reportId/dashboard",
        "/_basic-layout/reports/$reportId/"
      ]
    },
    "/_clear-layout": {
      "filePath": "_clear-layout.tsx",
      "children": [
        "/_clear-layout/profile",
        "/_clear-layout/reports/$reportId/credit-list"
      ]
    },
    "/_custom-layout": {
      "filePath": "_custom-layout.tsx",
      "children": [
        "/_custom-layout/reports/$reportId/new-report"
      ]
    },
    "/_layout-without-sidebar": {
      "filePath": "_layout-without-sidebar.tsx",
      "children": [
        "/_layout-without-sidebar/reports/$reportsId/bi-analytics",
        "/_layout-without-sidebar/reports/$reportsId/stress-testing"
      ]
    },
    "/apps": {
      "filePath": "apps.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/reports": {
      "filePath": "reports.tsx"
    },
    "/_clear-layout/profile": {
      "filePath": "_clear-layout/profile.tsx",
      "parent": "/_clear-layout"
    },
    "/_basic-layout/reports/$reportId/dashboard": {
      "filePath": "_basic-layout/reports/$reportId/dashboard.tsx",
      "parent": "/_basic-layout"
    },
    "/_clear-layout/reports/$reportId/credit-list": {
      "filePath": "_clear-layout/reports/$reportId/credit-list.tsx",
      "parent": "/_clear-layout"
    },
    "/_custom-layout/reports/$reportId/new-report": {
      "filePath": "_custom-layout/reports/$reportId/new-report.tsx",
      "parent": "/_custom-layout"
    },
    "/_layout-without-sidebar/reports/$reportsId/bi-analytics": {
      "filePath": "_layout-without-sidebar/reports/$reportsId/bi-analytics.tsx",
      "parent": "/_layout-without-sidebar"
    },
    "/_layout-without-sidebar/reports/$reportsId/stress-testing": {
      "filePath": "_layout-without-sidebar/reports/$reportsId/stress-testing.tsx",
      "parent": "/_layout-without-sidebar"
    },
    "/_basic-layout/reports/$reportId/": {
      "filePath": "_basic-layout/reports/$reportId/index.tsx",
      "parent": "/_basic-layout"
    }
  }
}
ROUTE_MANIFEST_END */
