name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        uses: D3rHase/ssh-command-action@latest
        with:
          host: banko.stacklevel.group
          port: 64751
          user: jenkins
          private_key: |-
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAueV3iJfQLnY9/87iklH7gOuGPF8xJv7qqpPnZwCLpjLslRO/8xSj
            lpBq34e5iTpEJdIpHKrATuLQC68uZUue7a+nPVOT7pa1WcJy6mh31eT8eNXCBFKqd5CdYh
            dHOm5H5UEVhQd4qHgC/wb22EC3g7o4Wl4HljFc/fn+hRoVGs3FGiexxygajnCCn5xBLhwZ
            nM55fQPBigDKbthxixBHGDyFa164pQhFgfe85F08qxOk4J/3R4K3PGAS5OTCIuP26eT+eM
            +RySjfa0QIJcuwmmkX5GUAduF5N4cUkOP6Af3wCM4Pmn+AKOUtFdKLdzC4tKf59vkmzTx4
            sdVIRUppKnHytJxVRaV3C3nq/KB4qJwX3tsGir3Ys2AjsbuGP+yKIOcB66clJh4cm3AOYh
            EWhd93FWiEmKQ7ZsgXAP/TDc3rUWTlm1BqWRutFoTxKcX32rqljJao0+Qcxp+iBBg8j4U4
            Hmtv6ZUUpYpHTBNtEBBKVaYMNSzhlfQn/Shq0bt5AAAFkOPefb3j3n29AAAAB3NzaC1yc2
            EAAAGBALnld4iX0C52Pf/O4pJR+4DrhjxfMSb+6qqT52cAi6Yy7JUTv/MUo5aQat+HuYk6
            RCXSKRyqwE7i0AuvLmVLnu2vpz1Tk+6WtVnCcupod9Xk/HjVwgRSqneQnWIXRzpuR+VBFY
            UHeKh4Av8G9thAt4O6OFpeB5YxXP35/oUaFRrNxRonsccoGo5wgp+cQS4cGZzOeX0DwYoA
            ym7YcYsQRxg8hWteuKUIRYH3vORdPKsTpOCf90eCtzxgEuTkwiLj9unk/njPkcko32tECC
            XLsJppF+RlAHbheTeHFJDj+gH98AjOD5p/gCjlLRXSi3cwuLSn+fb5Js08eLHVSEVKaSpx
            8rScVUWldwt56vygeKicF97bBoq92LNgI7G7hj/siiDnAeunJSYeHJtwDmIRFoXfdxVohJ
            ikO2bIFwD/0w3N61Fk5ZtQalkbrRaE8SnF99q6pYyWqNPkHMafogQYPI+FOB5rb+mVFKWK
            R0wTbRAQSlWmDDUs4ZX0J/0oatG7eQAAAAMBAAEAAAGAOPPvA8ezLdDnHMzXCIoaejxuU2
            e8qNxXq+wFbL6zijc22VOELuaHWfUj8RjlhH/36fhxxQkhQunlYHcKyVj6N4rlu3m0LFg6
            9mWHDH72G+98VE71Epr7BAen2CoWlfW8jCW9AJUx57dg/540GTv2nWJ7ql/9hgvYmC0zx7
            aeeahKN0GrCz+jpzkcI+dc5tIQHMT7Xow8itnEK2KfosHZbjj4jVUnT9Rxayip0/Mmx6kM
            jg8kVOHc3p/2me7l9YeOk+7RWQJpnmMP0nPxayJOhsmxLyETGZr2StJW3z433MFL2BfsQD
            2eHNZnxB/V1Ki6u9hXcwhCa9ea1323FwZ8MEaHsYTKYM3ZBVxoslWuV9Si3QiWYDnC2q+3
            hyF2ioCt1UxuK+SagM3vg6smMbs/IoLQc5iBRk4ZnuWt5gkHW068m8U+1R/HbKXdePUdQl
            M8XfK7P4V4mYvZ3wu+hUipwb9ajaB3EuCskDVmUqYO3SG0hlYdhth5g9K2588JdZQTAAAA
            wQCZQn+dqdTYoTiAkYhfdNjn8fQYu9+TT1cVcutx9O+bw2BY51tqJINmXAzx3Yc0D/JAmE
            DLDZMz4IPj7NG/uHhkEtW55e0Hm3lRtXoIcpcNBNW2M/Qk/M872a5H02mSaUM+nmFQIgbE
            rrRK8I7qjsZY0pYhWyC1itadbrVOCtuqkSO40rl/L6qIedkPmPZUlFvlmeQQtjwVeZcjfa
            E9bDG6f18eI1yYTuofOP03EZTqiBRMP6ozjy/Yg9n5Iq9jxYwAAADBAOXVw5U1jqy3E4WZ
            mO65SLd7uX1QXRvh9GQsSe0TWJApU+XOnraUkvcyK3n6FaIRTrKKvWUZerrNbMDSe7Ms0x
            4aU8VMsTyA+lV/glj1R+pRWPCe0cCkiBCmAG1HZ0KoeXuqxLQOzRkMHiBKU2RJvjnp/k6o
            Ze14O95Q+a254iO6rkuHLlMNc9LbEwQ0lsC9LpF1d36bt2qOJipXurPcxP8S1p4En86NgF
            19uWrQo7wML1k5i4L8+uO944mthK8glwAAAMEAzw8rSQsXAo2tjvTQHSK3ot5gCxYdOuFU
            CMZ5qFIn9qHM0URmro+P7cRqP04ZLBomVJ5DLQgaVRPUw8k+qSJ5FvkS7UpZ0SeTKtAzBC
            sW3f0W+Sf5IoFdybPrX5+2AbGVNqHoXLGnaG/wJHO0XOTlBwbh4Bq0Gb2352KISCzgQ9cM
            AW/05enSMB9pg/3LYCxUqPa6Fy0yByysc6BMVLlsYJajTelbbsfpvvMAvmDm1ERYFVKdnQ
            qSMSdsbAJjq3ZvAAAAFGdpdGh1Yl9hY3Rpb25zX0JhbmtvAQIDBAUG
            -----END OPENSSH PRIVATE KEY-----
          command: |
            [ ! -d /var/www/server-banko ] && git -C /var/www clone git@github.com:egorchecpc/server-banko.git;
            cd /var/www/server-banko;
            git pull origin main;
            cp -vf .env.dist .env; cp -vf frontend/.env.dist frontend/.env;
            docker compose up -d --build --force-recreate
